# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
 project 'Barcza GSC.xcodeproj'
target 'Barcza GSC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Barcza GSC
  pod 'SDWebImage', '~> 4.0'
  pod 'SVProgressHUD'
  pod 'RealmSwift'
  pod 'SwiftyBeaver'
  pod "PromiseKit", "~> 4.4"
  pod "PromiseKit/Foundation", " ~> 4.0"
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'RevealingSplashView'
  
  target 'Barcza GSCTests' do
    inherit! :search_paths
    
    pod "PromiseKit", "~> 4.4"
    pod "PromiseKit/Foundation", " ~> 4.0"
  end

end
